# Generated by Django 4.0.5 on 2022-06-25 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_remove_todo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
